### ISSUE TITLE
templatetag to render non-field-errors

### ISSUE THREAD

**Issue by stefanfoulis** [alesdotio/django-standard-form#1]
and possibly render non-field-errors at the top of the form by default when using `{% standard_form form %}`

**Comment by alesdotio** [comment]
you could just include the template like here https://github.com/alesdotio/django-standard-form/blob/master/standard_form/templates/standard_form/form.html#L2

and it is included on top by default

**Comment by stefanfoulis** [comment]
yes, sorry. I had a different issue with my form that prevented the rendering. sorry for the noise.
